Fix compilation with Qt < 5.14; QWheelEvent::position was added in 5.14 ("This function was introduced in Qt 5.14.", https://doc.qt.io/qt-5/qwheelevent.html#position)
\QuickQanava\master\src\qanNavigable.cpp(443,23): error C2039: 'position': is not a member of 'QWheelEvent'
\Qt\5.13.0\msvc2015_64\include\QtGui/qevent.h(173): message : see declaration of 'QWheelEvent'
Done building project "QuickQanava.vcxproj" -- FAILED.